name: 'Contracts Code Quality'

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "contracts/**"
      - "packages/**"
      - "scripts/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Install make
        run: |
          sudo apt-get install make

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Stellar
        run: |
          sh ./scripts/install_stellar.sh

      - name: Test
        run: |
          make test